# Generated by Django 5.0.6 on 2024-07-15 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latin_name', models.CharField(max_length=100)),
                ('Fr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Eng_name', models.CharField(blank=True, max_length=100, null=True)),
                ('User_Bird', models.ManyToManyField(blank=True, related_name='birds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL_Song', models.CharField(max_length=100)),
                ('List_Other_Birds', models.CharField(blank=True, max_length=100)),
                ('Id_bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.bird')),
            ],
        ),
    ]
