# Generated by Django 5.0.6 on 2024-08-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='List_Other_Birds',
            field=models.JSONField(default=list),
        ),
    ]
